import "@/styles/globals.css";

import { geistMono, geistSans, inter } from "@/utils/fonts";

import type { Metadata } from "next";
import { cn } from "@/utils/cn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "antialiased",
          geistSans.variable,
          geistMono.variable,
          inter.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}

